import "./globals.css";
import Header from "./components/Header";
import Head from "next/head";

export const metadata = {
	title: "Poem Next App",
	description: "Generated by aasoft.ir",
};

export default function RootLayout({ children }) {
	return (
		<html
			lang="en"
			className="h-screen bg-cover bg-gradient-to-l from-slate-900 to-purple-900"
		>
			<Head>
				<link rel="shortcut icon" href="/public/logo.png" />
			</Head>
			<body
				className={`font-vazir bg-cover bg-no-repeat w-[100vw] overflow-x-hidden `}
			>
				<Header />
				{children}
			</body>
		</html>
	);
}
